CC = cl
	
all: main

nob.exe:
	$(CC) -out:build\nob.exe nob.c

main: build\nob.exe
	build\nob.exe

clean:
	del *.exe *.exp *.lib *.obj *.dll *.pdb *.idb *.ilk *.log
	rmdir /s /q build
	mkdir build
	type nul > build\.gitkeep
