all: main

build/nob:
	gcc -o build/nob nob.c

main: build/nob
	./build/nob

clean:
	rm -rf build/ 
	rm -f *.log
	mkdir build/
	touch build/.gitkeep

publish:
	rm -rf release/linux/*
	cp build/swimd.so release/linux/
	cp build/libgit2.so release/linux/
	cp build/version release/linux/
	touch release/linux/.gitkeep
