all: main

build/nob.exe:
	cl /Fe:build\nob.exe nob.c

main: build/nob.exe
	build\nob.exe

clean:
	del *.exe *.exp *.lib *.obj *.dll *.pdb *.idb *.ilk *.log *.old
	rmdir /s /q build
	mkdir build
	type nul > build\.gitkeep

publish:
	rmdir /s /q release\win
	mkdir build
	copy build\swimd.dll release\win\
	copy build\git2.dll release\win\
	copy build\version release\win\
	type nul > release\win
